[package]
name = "hoi4save"
version = "0.3.4"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"
exclude = ["/assets/*", "/fuzz/*"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rakaly/hoi4save.git"
description = "Ergonomically work with HOI4 saves"
keywords = ["hoi4", "ironman"]
categories = ["parsing"]

[dependencies]
jomini = { version = "0.26.0", features = ["json"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
zip = { version =  "0.6", default-features = false, features = ["deflate"] }
attohttpc = "0.26"

[profile.test]
opt-level = 3
lto = "thin"

[profile.bench]
lto = true
codegen-units = 1

[profile.release]
lto = true
codegen-units = 1
